#spring:
#  r2dbc:
#    url: "r2dbc:postgresql://localhost:5432/db_srcrud"
#    username: postgres
#    password: 123456
#    properties:
#      schema: schema_srcrud
spring:
  r2dbc:
    url: "r2dbc:pool:mysql://localhost:3306/demo"
    username: demo
    password: 123456

logging:
  level:
    root: debug


